"""Writes src/server/World/HangarVoxels.luau from every model in models/.

    python tools/hangar_voxels/export.py

Plain Python (no Blender needed). Each model's voxels are merged into boxes
(vox.Vox.greedy) and written as data HangarBuilder builds Parts from.
"""

import importlib
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent
OUT = ROOT / "src" / "server" / "World" / "HangarVoxels.luau"

sys.path.insert(0, str(HERE))


def lua_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_number(n):
    return repr(round(n, 3)) if isinstance(n, float) else str(n)


def entry_lua(key, entry):
    fields = [f"name = {lua_string(entry.get('name', key))}", f"color = {lua_string(entry['color'])}"]
    fields.append(f"material = {lua_string(entry.get('material', 'SmoothPlastic'))}")
    if entry.get("transparency"):
        fields.append(f"transparency = {lua_number(entry['transparency'])}")
    if entry.get("collide") is False:
        fields.append("collide = false")
    if entry.get("group"):
        fields.append(f"group = {lua_string(entry['group'])}")
    if entry.get("pulse"):
        a, b = entry["pulse"]
        fields.append(f"pulse = {{ {lua_number(a)}, {lua_number(b)} }}")
    return "{ " + ", ".join(fields) + " }"


def model_lua(model):
    keys = sorted({b[6] for b in model.greedy()})
    index = {k: i + 1 for i, k in enumerate(keys)}
    lines = [f"\t{model.id} = {{", "\t\tpalette = {"]
    for k in keys:
        lines.append(f"\t\t\t{entry_lua(k, model.palette[k])},")
    lines.append("\t\t},")
    lines.append("\t\tboxes = {")
    for (x, y, z, sx, sy, sz, key) in model.greedy():
        lines.append(f"\t\t\t{{ {x}, {y}, {z}, {sx}, {sy}, {sz}, {index[key]} }},")
    lines.append("\t\t},")
    lines.append("\t},")
    return lines


def main():
    ids = sorted(p.stem for p in (HERE / "models").glob("*.py") if p.stem != "__init__")
    out = [
        "--!strict",
        "-- GENERATED by tools/hangar_voxels/export.py from the Blender voxel designs",
        "-- in tools/hangar_voxels/models. Do not edit by hand: change the model",
        "-- script, preview it in Blender, and run the exporter again.",
        "--",
        "-- Per hangar upgrade id: a palette (part look) and boxes, each",
        "-- { x, y, z, sizeX, sizeY, sizeZ, paletteIndex } in 1-stud voxels in",
        "-- station space from the building's floor point (min corner).",
        "",
        "export type Entry = {",
        "\tname: string,",
        "\tcolor: string,",
        "\tmaterial: string,",
        "\ttransparency: number?,",
        "\tcollide: boolean?,",
        "\tgroup: string?,",
        "\tpulse: { number }?,",
        "}",
        "",
        "export type VoxelModel = {",
        "\tpalette: { Entry },",
        "\tboxes: { { number } },",
        "}",
        "",
        "local MODELS: { [string]: VoxelModel } = {",
    ]
    total = 0
    for model_id in ids:
        model = importlib.import_module(f"models.{model_id}").build()
        assert model.id == model_id, model_id
        out += model_lua(model)
        count = len(model.greedy())
        total += count
        print(f"{model_id}: {len(model.cells)} voxels -> {count} parts")
    out += ["}", "", "return MODELS", ""]
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} ({total} parts)")


if __name__ == "__main__":
    main()
